import { existsSync, mkdirSync, readdirSync, rmSync, statSync } from 'node:fs'
import { dirname, extname, join, relative } from 'node:path'
import {
  CATALOG,
  ROOT,
  buildIndexes,
  computeCatalogHash,
  loadPackRecords,
  loadRegistry,
  loadSkillRecords,
  parseYaml,
  prefixFor,
  readJsonl,
  readText,
  sha256,
  slug,
  sortDeep,
  stableStringify,
  validateCatalog,
  writeTextAtomic,
} from '../../../catalog-data/scripts/lib/catalog-lib.mjs'

export const GENERATED_BANNER = '<!-- GENERATED BY catalog-publishing. DO NOT EDIT DIRECTLY. -->'
export const GENERATOR = 'catalog-publishing@1'
const DOCS = join(ROOT, 'docs')

export function renderAll() {
  const validation = validateCatalog({ strict: true })
  if (!validation.ok) {
    throw new Error(`catalog validation failed before publishing:\n${validation.errors.join('\n')}`)
  }

  const manifest = buildIndexes()
  const model = loadModel(manifest)
  const pages = buildRenderedPages(model)
  cleanGeneratedMarkdown()
  for (const [path, content] of pages.entries()) writeTextAtomic(path, content)
  ensureGeneratedDirectories()
  return { catalog_hash: model.catalogHash, generated_at: model.generatedAt, written: [...pages.keys()].map((path) => relative(ROOT, path)).sort() }
}

export function checkDocsDrift() {
  const validation = validateCatalog({ strict: true })
  if (!validation.ok) return { ok: false, drift: validation.errors.map((message) => ({ type: 'validation-error', message })) }

  const model = loadModel(readManifest())
  const expected = buildRenderedPages(model)
  const drift = []
  for (const [path, expectedContent] of expected.entries()) {
    if (!existsSync(path)) drift.push({ path: relative(ROOT, path), type: 'missing' })
    else if (readText(path) !== expectedContent) drift.push({ path: relative(ROOT, path), type: 'changed' })
  }

  for (const path of [join(ROOT, 'README.md'), ...listMarkdownFiles(DOCS)]) {
    if (expected.has(path)) continue
    if (isGeneratedFile(path)) drift.push({ path: relative(ROOT, path), type: 'stale-generated' })
    else if (path.startsWith(DOCS)) drift.push({ path: relative(ROOT, path), type: 'unmanaged-docs-markdown' })
  }

  return { ok: drift.length === 0, drift, expected: [...expected.keys()].map((path) => relative(ROOT, path)).sort() }
}

export function checkLinks() {
  const generated = [join(ROOT, 'README.md'), ...listMarkdownFiles(DOCS)].filter((path) => existsSync(path) && isGeneratedFile(path))
  const errors = []
  const linkPattern = /\[[^\]]+\]\(([^)]+)\)/g
  for (const path of generated) {
    const text = readText(path)
    for (const match of text.matchAll(linkPattern)) {
      const raw = match[1].trim()
      if (!raw || raw.startsWith('#') || /^[a-z]+:/i.test(raw) || raw.startsWith('mailto:')) continue
      const withoutAnchor = raw.split('#')[0]
      if (!withoutAnchor) continue
      const target = join(dirname(path), withoutAnchor)
      if (!existsSync(target)) errors.push(`${relative(ROOT, path)} links to missing ${raw}`)
    }
  }
  return { ok: errors.length === 0, errors, checked_files: generated.map((path) => relative(ROOT, path)).sort() }
}

function buildRenderedPages(model) {
  const pages = new Map()
  pages.set(join(ROOT, 'README.md'), renderReadme(model))
  pages.set(join(DOCS, 'packs', 'README.md'), renderPacksIndex(model))
  pages.set(join(DOCS, 'skills', 'README.md'), renderSkillsIndex(model))
  pages.set(join(DOCS, 'sources', 'README.md'), renderSourcesIndex(model))
  pages.set(join(DOCS, 'domains', 'README.md'), renderDomainsIndex(model))
  pages.set(join(DOCS, 'reports', 'README.md'), renderReportsIndex(model))

  for (const pack of model.packs) pages.set(join(DOCS, 'packs', slug(pack.domain), `${pack.pack_id}.md`), renderPackPage(model, pack))
  for (const skill of model.skills) pages.set(join(DOCS, 'skills', prefixFor(skill.canonical_skill_id), `${skill.canonical_skill_id}.md`), renderSkillPage(model, skill))
  for (const source of model.sources) pages.set(join(DOCS, 'sources', `${source.source_id}.md`), renderSourcePage(model, source))
  for (const domain of model.domains) pages.set(join(DOCS, 'domains', `${slug(domain.id)}.md`), renderDomainPage(model, domain))
  return pages
}

function loadModel(manifest) {
  const catalogHash = computeCatalogHash()
  const generatedAt = stableGeneratedAt(manifest, catalogHash)
  const skills = loadSkillRecords().map(({ path, record }) => ({ ...record, __path: relative(ROOT, path), __hash: sha256(readText(path)) })).sort((a, b) => a.canonical_skill_id.localeCompare(b.canonical_skill_id))
  const registry = loadRegistry()
  const sources = registry.sources.map((source) => ({ ...source, __path: 'catalog/sources/registry.yaml', __hash: sha256(stableStringify(source)) })).sort((a, b) => a.source_id.localeCompare(b.source_id))
  const packs = loadPackRecords('published').map(({ path, record }) => ({ ...record, __path: relative(ROOT, path), __hash: sha256(readText(path)) })).sort((a, b) => a.pack_id.localeCompare(b.pack_id))
  const relations = readJsonl(join(CATALOG, 'relations', 'edges-00000.jsonl'))
  const analyses = new Map(skills.map((skill) => [skill.canonical_skill_id, loadAnalysisSummary(skill.analysis?.path)]))
  const domains = deriveDomains(skills, packs)
  return { catalogHash, generatedAt, manifest, skills, sources, packs, relations, analyses, domains }
}

function readManifest() {
  const path = join(CATALOG, 'indexes', 'manifest.json')
  if (!existsSync(path)) return null
  try { return JSON.parse(readText(path)) } catch { return null }
}

function stableGeneratedAt(manifest, catalogHash) {
  const existing = readFrontmatter(join(ROOT, 'README.md'))
  if (existing?.catalog_hash === catalogHash && existing.generated_at) return existing.generated_at
  if (manifest?.catalog_hash === catalogHash && manifest.generated_at) return manifest.generated_at
  return new Date().toISOString()
}

function readFrontmatter(path) {
  if (!existsSync(path)) return null
  const text = readText(path)
  const match = text.match(/^<!-- GENERATED BY catalog-publishing\. DO NOT EDIT DIRECTLY\. -->\n---\n([\s\S]*?)\n---/)
  if (!match) return null
  try { return parseYaml(match[1], `${relative(ROOT, path)} frontmatter`) } catch { return null }
}

function deriveDomains(skills, packs) {
  const ids = [...new Set([...skills.flatMap((skill) => skill.capabilities?.domains ?? []), ...packs.map((pack) => pack.domain)].filter(Boolean))].sort()
  return ids.map((id) => ({
    id,
    skills: skills.filter((skill) => (skill.capabilities?.domains ?? []).includes(id)),
    packs: packs.filter((pack) => pack.domain === id),
    sources: [...new Set(skills.filter((skill) => (skill.capabilities?.domains ?? []).includes(id)).map((skill) => skill.source?.source_id).filter(Boolean))].sort(),
  }))
}

function loadAnalysisSummary(path) {
  if (!path) return { available: false, summary: 'Analysis pending.' }
  const full = join(ROOT, path)
  if (!existsSync(full)) return { available: false, summary: 'Analysis pending.' }
  const text = readText(full)
  const purpose = section(text, 'Core Purpose')
  return { available: true, summary: purpose || 'Analysis available.', hash: sha256(text) }
}

function section(text, heading) {
  const pattern = new RegExp(`## ${escapeRegExp(heading)}\\n([\\s\\S]*?)(?=\\n## |$)`)
  const match = text.match(pattern)
  return match ? match[1].trim() : ''
}

function renderReadme(model) {
  const featured = model.packs.length ? bulletList(model.packs.slice(0, 10).map((pack) => `[${pack.name}](docs/packs/${slug(pack.domain)}/${pack.pack_id}.md) — ${pack.domain} (${score(pack.evaluation?.score)})`)) : 'No published packs yet. Run the catalog workflow to synthesize and evaluate candidates.'
  const domains = model.domains.length ? bulletList(model.domains.map((domain) => `[${domain.id}](docs/domains/${slug(domain.id)}.md) — ${domain.packs.length} packs, ${domain.skills.length} skills`)) : 'No domains indexed yet.'
  return page(recordFrontmatter(model, 'readme', 'root', 'catalog/indexes/manifest.json', model.catalogHash, null), `# Skill Intelligence Catalog

This repository is a generated catalog of researched agent skills, sources, analyses, relationships, and evaluated skill packs. It is operated by Synergy project skills under \`.synergy/skill/\`; \`catalog/\` is the single source of truth.

## Catalog Status

${countsLine(model)}

- Catalog hash: \`${model.catalogHash}\`
- Generated at: \`${model.generatedAt}\`

## Featured Packs

${featured}

## Browse by Domain

${domains}

## Full Catalog

- [Packs](docs/packs/README.md)
- [Skills](docs/skills/README.md)
- [Sources](docs/sources/README.md)
- [Domains](docs/domains/README.md)
- [Reports](docs/reports/README.md)

## Contribution Boundary

Do not hand-edit generated catalog pages. Durable facts belong in \`catalog/\` through \`catalog-data\` scripts, then README/docs are regenerated by \`catalog-publishing\`.
`)
}

function renderPacksIndex(model) {
  const rows = model.packs.length ? table(['Pack', 'Domain', 'Status', 'Score'], model.packs.map((pack) => [`[${pack.name}](${slug(pack.domain)}/${pack.pack_id}.md)`, pack.domain, pack.status, score(pack.evaluation?.score)])) : 'No published packs yet.'
  return page(indexFrontmatter(model, 'pack_index', 'docs/packs/README.md'), `# Published Packs\n\n${rows}\n`)
}

function renderSkillsIndex(model) {
  const rows = model.skills.length ? table(['Skill', 'Status', 'Domains', 'Source'], model.skills.map((skill) => [`[${skill.display_name}](${prefixFor(skill.canonical_skill_id)}/${skill.canonical_skill_id}.md)`, skill.status, (skill.capabilities?.domains ?? []).join(', ') || '—', skill.source?.source_id ?? '—'])) : 'No skills indexed yet.'
  return page(indexFrontmatter(model, 'skill_index', 'docs/skills/README.md'), `# Skills\n\n${rows}\n`)
}

function renderSourcesIndex(model) {
  const rows = model.sources.length ? table(['Source', 'Status', 'Type', 'License'], model.sources.map((source) => [`[${source.name}](${source.source_id}.md)`, source.status, source.type, licenseText(source.license)])) : 'No sources tracked yet.'
  return page(indexFrontmatter(model, 'source_index', 'docs/sources/README.md'), `# Sources\n\n${rows}\n`)
}

function renderDomainsIndex(model) {
  const rows = model.domains.length ? table(['Domain', 'Packs', 'Skills', 'Sources'], model.domains.map((domain) => [`[${domain.id}](${slug(domain.id)}.md)`, String(domain.packs.length), String(domain.skills.length), String(domain.sources.length)])) : 'No domains indexed yet.'
  return page(indexFrontmatter(model, 'domain_index', 'docs/domains/README.md'), `# Domains\n\n${rows}\n`)
}

function renderReportsIndex(model) {
  return page(indexFrontmatter(model, 'report_index', 'docs/reports/README.md'), '# Public Reports\n\nPublic report summaries will appear here after nightly automation has report content safe for publication.\n')
}

function renderPackPage(model, pack) {
  const members = pack.members?.length ? table(['Skill', 'Role', 'Stage', 'Pinned Version', 'Reason'], pack.members.map((member) => {
    const skill = model.skills.find((item) => item.canonical_skill_id === member.skill_id)
    const skillLink = skill ? `../../skills/${prefixFor(skill.canonical_skill_id)}/${skill.canonical_skill_id}.md` : ''
    return [skill ? `[${skill.display_name}](${skillLink})` : member.skill_id, member.role, member.stage, code(member.version_id), member.inclusion_reason]
  })) : 'No members recorded.'
  const stages = pack.workflow?.stages?.length ? bulletList(pack.workflow.stages.map((stage) => typeof stage === 'string' ? stage : `${stage.name ?? stage.stage ?? 'stage'} — ${stage.description ?? ''}`)) : 'No workflow stages recorded.'
  return page(recordFrontmatter(model, 'pack', pack.pack_id, pack.__path, pack.__hash, pack.evaluation?.evaluation_id), `# ${pack.name}

${statusBanner(pack.status)}

## What This Pack Is

${pack.intent}

## When to Use It

Use this pack for \`${pack.domain}\` work when the member skills match the task and current version pins remain fresh.

## Member Skills

${members}

## Workflow Stages

${stages}

## Why This Combination Works

${listOrFallback(pack.compatibility?.complements, 'No complement evidence recorded.')}

## Overlap and Conflict Handling

- Overlaps: ${inlineList(pack.compatibility?.overlaps)}
- Conflicts: ${inlineList(pack.compatibility?.conflicts)}

## Source Evidence

- Analysis paths: ${inlineList(pack.evidence?.analysis_paths)}
- Relation edges: ${inlineList(pack.evidence?.relation_edges)}

## Evaluation

- Status: ${pack.evaluation?.status ?? 'pending'}
- Score: ${score(pack.evaluation?.score)}
- Evaluation ID: ${pack.evaluation?.evaluation_id ?? '—'}

## Version History

- Version: ${pack.version}
- Updated: ${pack.updated_at}
`)
}

function renderSkillPage(model, skill) {
  const analysis = model.analyses.get(skill.canonical_skill_id)
  const relatedEdges = model.relations.filter((edge) => edge.subject === skill.canonical_skill_id || edge.object === skill.canonical_skill_id)
  const relatedPacks = model.packs.filter((pack) => (pack.members ?? []).some((member) => member.skill_id === skill.canonical_skill_id))
  return page(recordFrontmatter(model, 'skill', skill.canonical_skill_id, skill.__path, skill.__hash, null), `# ${skill.display_name}

${statusBanner(skill.status)}

## Summary

${analysis?.summary ?? 'Analysis pending.'}

## Source and License

- Source: ${skill.source?.source_id ?? '—'}
- Path: ${skill.source?.path ?? '—'}
- License: ${licenseText(skill.source?.license)}

## Capabilities

- Domains: ${inlineList(skill.capabilities?.domains)}
- Task types: ${inlineList(skill.capabilities?.task_types)}
- Workflow stages: ${inlineList(skill.capabilities?.workflow_stages)}
- Atomic capabilities: ${inlineList(skill.capabilities?.atomic_capabilities)}

## Best Used For / Not For

Use when the trigger semantics and workflow stage match the task. Do not use when required tools, permissions, license, or confidence do not fit the current run.

## Inputs / Outputs

- Inputs: ${inlineList(skill.interfaces?.inputs)}
- Outputs: ${inlineList(skill.interfaces?.outputs)}
- Handoff outputs: ${inlineList(skill.interfaces?.handoff_outputs)}

## Related Packs

${relatedPacks.length ? bulletList(relatedPacks.map((pack) => `[${pack.name}](../../packs/${slug(pack.domain)}/${pack.pack_id}.md)`)) : 'No published packs use this skill yet.'}

## Related Skills

${relatedEdges.length ? bulletList(relatedEdges.map((edge) => `${edge.subject} ${edge.predicate} ${edge.object} (${edge.weight})`)) : 'No relation edges recorded yet.'}

## Public Analysis Summary

${analysis?.summary ?? 'Analysis pending.'}

## Confidence and Limitations

- Quality score: ${score(skill.quality?.score)}
- Confidence: ${skill.quality?.confidence ?? 'unknown'}
- Risk surfaces: ${inlineList(skill.risk?.risk_surfaces)}
`)
}

function renderSourcePage(model, source) {
  const skills = model.skills.filter((skill) => skill.source?.source_id === source.source_id)
  const packs = model.packs.filter((pack) => (pack.members ?? []).some((member) => skills.some((skill) => skill.canonical_skill_id === member.skill_id)))
  return page(recordFrontmatter(model, 'source', source.source_id, source.__path, source.__hash, null), `# ${source.name}

${statusBanner(source.status)}

## Overview

- URL: ${source.url ?? '—'}
- Type: ${source.type}
- License: ${licenseText(source.license)}

## Health

- Last checked: ${source.state?.last_checked_at ?? '—'}
- Last success: ${source.state?.last_success_at ?? '—'}
- Last ref: ${source.state?.last_ref ?? '—'}
- Consecutive failures: ${source.state?.consecutive_failures ?? 0}

## Tracked Skills

${skills.length ? bulletList(skills.map((skill) => `[${skill.display_name}](../skills/${prefixFor(skill.canonical_skill_id)}/${skill.canonical_skill_id}.md)`)) : 'No skills tracked for this source yet.'}

## Packs Using This Source

${packs.length ? bulletList(packs.map((pack) => `[${pack.name}](../packs/${slug(pack.domain)}/${pack.pack_id}.md)`)) : 'No published packs use this source yet.'}
`)
}

function renderDomainPage(model, domain) {
  const sourceDistribution = domain.sources.length ? bulletList(domain.sources.map((sourceId) => `${sourceId}: ${domain.skills.filter((skill) => skill.source?.source_id === sourceId).length} skills`)) : 'No source distribution yet.'
  return page(recordFrontmatter(model, 'domain', domain.id, 'catalog/indexes/domain-catalog.jsonl', model.catalogHash, null), `# ${domain.id}

## Summary

This domain is derived from catalog skill capabilities and published pack domains.

## Published Packs

${domain.packs.length ? bulletList(domain.packs.map((pack) => `[${pack.name}](../packs/${slug(pack.domain)}/${pack.pack_id}.md)`)) : 'No published packs yet.'}

## Relevant Skills

${domain.skills.length ? bulletList(domain.skills.map((skill) => `[${skill.display_name}](../skills/${prefixFor(skill.canonical_skill_id)}/${skill.canonical_skill_id}.md)`)) : 'No skills indexed for this domain yet.'}

## Source Distribution

${sourceDistribution}

## Coverage Gaps

Coverage gaps are generated by evaluation reports when enough catalog data exists.

## Recent Changes

No public recent-change summary has been generated yet.
`)
}

function page(frontmatter, body) {
  return `${GENERATED_BANNER}\n---\n${frontmatterYaml(frontmatter)}---\n\n${body.trim()}\n`
}

function frontmatterYaml(frontmatter) {
  return Object.entries(sortDeep(frontmatter)).map(([key, value]) => `${key}: ${JSON.stringify(value)}`).join('\n') + '\n'
}

function recordFrontmatter(model, sourceType, sourceId, sourceRecord, sourceHash, evaluationId) {
  return {
    catalog_hash: model.catalogHash,
    evaluation_id: evaluationId,
    generated: true,
    generated_at: model.generatedAt,
    generator: GENERATOR,
    source_hash: sourceHash,
    source_id: sourceId,
    source_record: sourceRecord,
    source_type: sourceType,
  }
}

function indexFrontmatter(model, sourceType, sourceRecord) {
  return recordFrontmatter(model, sourceType, sourceType, sourceRecord, model.catalogHash, null)
}

function countsLine(model) {
  return bulletList([
    `${model.packs.length} published packs`,
    `${model.skills.length} indexed skills`,
    `${model.sources.length} tracked sources`,
    `${model.domains.length} domains`,
  ])
}

function table(headers, rows) {
  return [`| ${headers.join(' | ')} |`, `| ${headers.map(() => '---').join(' | ')} |`, ...rows.map((row) => `| ${row.map((cell) => String(cell ?? '—').replace(/\n/g, ' ')).join(' | ')} |`)].join('\n')
}

function bulletList(items) {
  return items.map((item) => `- ${item}`).join('\n')
}

function inlineList(value) {
  if (!value || value.length === 0) return '—'
  return Array.isArray(value) ? value.map((item) => typeof item === 'string' ? item : JSON.stringify(item)).join(', ') : String(value)
}

function listOrFallback(value, fallback) {
  return value && value.length ? bulletList(value.map((item) => typeof item === 'string' ? item : JSON.stringify(item))) : fallback
}

function licenseText(license) {
  if (!license) return 'unknown'
  const spdx = license.spdx ?? 'unknown'
  return `${spdx}${license.verified ? ' (verified)' : ' (unverified)'}`
}

function statusBanner(status) {
  if (!status || ['active', 'published'].includes(status)) return ''
  return `> Status: **${status}**`
}

function score(value) {
  return typeof value === 'number' ? value.toFixed(2) : '—'
}

function code(value) {
  return value ? `\`${value}\`` : '—'
}

function cleanGeneratedMarkdown() {
  for (const path of listMarkdownFiles(DOCS)) {
    if (isGeneratedFile(path)) rmSync(path, { force: true })
  }
}

function ensureGeneratedDirectories() {
  for (const dir of [join(DOCS, 'packs', 'by-domain'), join(DOCS, 'skills', 'by-domain'), join(DOCS, 'skills', 'by-source')]) mkdirSync(dir, { recursive: true })
}

function isGeneratedFile(path) {
  return extname(path) === '.md' && existsSync(path) && readText(path).startsWith(GENERATED_BANNER)
}

function listMarkdownFiles(dir) {
  if (!existsSync(dir)) return []
  const out = []
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry)
    const stat = statSync(path)
    if (stat.isDirectory()) out.push(...listMarkdownFiles(path))
    else if (path.endsWith('.md')) out.push(path)
  }
  return out.sort()
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}
